### ISSUE TITLE
where can i get Simplified Chinese conllu file?

### ISSUE THREAD

**Issue by yutaolife** [UniversalDependencies/UD_Chinese#3]
Dear UD,  would you please let me know that where can i get Simplified Chinese conllu file.  After i search all of UD zip, i found that all chinese zip is traditional chinese. what i mean that, tradition chinese zip file can use in Simplified Chinese?

**Comment by ermanh** [comment]
You can use a traditional-to-simplified converter (e.g. `mafan` module in
Python).

In general Chinese data should ideally be kept in traditional characters if
the source is already in traditional characters, because automatic
conversion is reliable from traditional to simplified, but not from
simplified to traditional, since simplified has collapsed a number of
characters together that are differentiated in traditional (the `mafan`
module mentioned above also has a simplified-to-traditional converter
function, but it's not reliable for this very reason).


On Aug 7, 2017 9:16 PM, "Yu Tao" <notifications@github.com> wrote:

Dear UD,

would you please let me know that where can i get Simplified Chinese
conllu file.  After i search all of UD zip, i found that all chinese
zip is traditional chinese. what i mean that, tradition chinese zip
file can use in Simplified Chinese?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/UniversalDependencies/UD_Chinese/issues/3>, or mute the
thread

**Comment by yutaolife** [comment]
@ermanh  Many thanks.  I know how to do this.
